// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3VVW5IB7Eg4FBHQLoKmULY8T75N7q3bA',
    appId: '1:235100919327:web:7cbb5290f764925fd7a72a',
    messagingSenderId: '235100919327',
    projectId: 'firebase-auth-package',
    authDomain: 'fir-auth-package-a82f5.firebaseapp.com',
    storageBucket: 'firebase-auth-package.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXHpdYRE8UFmoKkWlZBjcqmQbaK9iTLUo',
    appId: '1:235100919327:android:01041572da7a4c24d7a72a',
    messagingSenderId: '235100919327',
    projectId: 'firebase-auth-package',
    storageBucket: 'firebase-auth-package.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFbSGdv8zruiquAXHYmTnsYRzBhTLyYrk',
    appId: '1:235100919327:ios:112e950bc7b95f53d7a72a',
    messagingSenderId: '235100919327',
    projectId: 'firebase-auth-package',
    storageBucket: 'firebase-auth-package.appspot.com',
    iosBundleId: 'com.example.firebaseAuthPackage',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCFbSGdv8zruiquAXHYmTnsYRzBhTLyYrk',
    appId: '1:235100919327:ios:768b9b33a5b0d15ad7a72a',
    messagingSenderId: '235100919327',
    projectId: 'firebase-auth-package',
    storageBucket: 'firebase-auth-package.appspot.com',
    iosBundleId: 'com.example.firebaseAuthPackage.RunnerTests',
  );
}
